"""Every signal name that has ever been released still resolves.

Registered names are the strategy-facing contract. A saved strategy stores the name
as a string, so a name that stops resolving does not raise where the strategy lives
-- it raises at evaluation, inside a caller that treats the failure as "the signal
did not fire". A rename is therefore only safe with an alias behind it.

RELEASED_SIGNAL_NAMES is the union of the names registered in every released version
from v1.3.4 onward. Adding an entry is what shipping a new signal looks like. Removing
one is not permitted: retire a name by pointing it at its replacement with
RuleRegistry.alias(old, new), which is what makes this test pass again.

This test exists because the v2.0.0 rename of the four apo_* signals to
macd_line_* shipped without aliases while the chandelier_* and
volatility_stop_* renames in the same release shipped with them. Nothing compared
the alias list against the names already in circulation.
"""

from mangrove_kb.registry import RuleRegistry
from mangrove_kb.signals import (  # noqa: F401  -- imported for their registrations
    averaging,
    flow,
    momentum,
    onchain,
    oscillator,
    pattern,
    trend,
    volatility,
)

RELEASED_SIGNAL_NAMES = (
    'adi_bearish',
    'adi_bullish',
    'adosc_bearish',
    'adosc_bullish',
    'adosc_cross_down',
    'adosc_cross_up',
    'adx_bullish_di',
    'adx_strong_trend',
    'alligator_bearish',
    'alligator_bullish',
    'alligator_sleeping',
    'alma_cross_down',
    'alma_cross_up',
    'ao_bearish',
    'ao_bullish',
    'ao_zero_cross',
    'apo_bearish',
    'apo_bullish',
    'apo_cross_down',
    'apo_cross_up',
    'aroon_crossover',
    'aroon_down_trend',
    'aroon_up_trend',
    'atr_high_volatility',
    'atr_trailing_stop_flip_down',
    'atr_trailing_stop_flip_up',
    'atr_trailing_stop_long',
    'atr_trailing_stop_short',
    'bb_above_upper',
    'bb_below_lower',
    'bb_lower_breakout',
    'bb_squeeze',
    'bb_upper_breakout',
    'bearish_engulfing_trigger',
    'bearish_harami_trigger',
    'bearish_pattern_recent',
    'bearish_pin_bar_trigger',
    'bop_bearish',
    'bop_bullish',
    'bop_cross_down',
    'bop_cross_up',
    'bullish_engulfing_trigger',
    'bullish_harami_trigger',
    'bullish_pattern_recent',
    'bullish_pin_bar_trigger',
    'cci_overbought',
    'cci_oversold',
    'chandelier_long_stop_hit',
    'chandelier_short_stop_hit',
    'cl_above_low_offset',
    'cl_below_high_offset',
    'cl_high_offset_break',
    'cl_low_offset_break',
    'cmf_bearish',
    'cmf_bullish',
    'cmo_cross_down',
    'cmo_cross_up',
    'cmo_overbought',
    'cmo_oversold',
    'continuation_pattern_bearish',
    'continuation_pattern_bullish',
    'cumulative_return_positive',
    'cumulative_return_target',
    'daily_return_negative',
    'daily_return_positive',
    'dark_cloud_cover_trigger',
    'dc_lower_breakout',
    'dc_upper_breakout',
    'dema_cross_down',
    'dema_cross_up',
    'doji_trigger',
    'dpo_negative',
    'dpo_positive',
    'dragonfly_doji_trigger',
    'ema_cross_down',
    'ema_cross_up',
    'ema_crossover',
    'eom_bearish',
    'eom_bullish',
    'epma_cross_down',
    'epma_cross_up',
    'etf_inflow_spike',
    'etf_inflow_streak',
    'evening_star_trigger',
    'exchange_net_outflow',
    'exchange_outflow_spike',
    'force_bearish',
    'force_bullish',
    'funding_flip_positive',
    'funding_negative_regime',
    'gravestone_doji_trigger',
    'hammer_trigger',
    'hanging_man_trigger',
    'heikin_ashi_bearish',
    'heikin_ashi_bullish',
    'hma_cross_down',
    'hma_cross_up',
    'holder_concentration_falling',
    'holder_concentration_low',
    'ichimoku_bearish',
    'ichimoku_bullish',
    'ichimoku_tk_cross',
    'indecision_pattern_recent',
    'inside_bar_trigger',
    'inverted_hammer_trigger',
    'is_above_alma',
    'is_above_dema',
    'is_above_epma',
    'is_above_hma',
    'is_above_mama',
    'is_above_sma',
    'is_above_smma',
    'is_above_t3',
    'is_above_tema',
    'is_above_trima',
    'is_above_vwma',
    'kama_cross_down',
    'kama_cross_up',
    'kc_above_upper',
    'kc_below_lower',
    'kc_lower_breakout',
    'kc_upper_breakout',
    'kst_bearish_cross',
    'kst_bullish_cross',
    'kvo_bearish',
    'kvo_bearish_cross',
    'kvo_bullish',
    'kvo_bullish_cross',
    'lending_spread_low',
    'lending_spread_widening',
    'long_legged_doji_trigger',
    'ma_ribbon_bearish',
    'ma_ribbon_bullish',
    'ma_ribbon_tangled',
    'macd_bearish_cross',
    'macd_bullish_cross',
    'macd_line_cross_down',
    'macd_line_cross_up',
    'macd_line_negative',
    'macd_line_positive',
    'macd_positive',
    'mama_cross_down',
    'mama_cross_up',
    'marubozu_bearish_trigger',
    'marubozu_bullish_trigger',
    'mass_reversal_signal',
    'mfi_overbought',
    'mfi_oversold',
    'mom_bearish',
    'mom_bullish',
    'mom_cross_down',
    'mom_cross_up',
    'morning_star_trigger',
    'multi_tf_trend_bearish',
    'multi_tf_trend_bullish',
    'natr_high_volatility',
    'natr_low_volatility',
    'nr7_trigger',
    'nvi_bearish',
    'nvi_bullish',
    'obv_bearish',
    'obv_bullish',
    'outside_bar_trigger',
    'piercing_line_trigger',
    'ppo_bearish_cross',
    'ppo_bullish_cross',
    'price_above_ema',
    'psar_bearish',
    'psar_bullish',
    'psar_reversal',
    'pvo_bearish_cross',
    'pvo_bullish_cross',
    'reversal_pattern_bearish',
    'reversal_pattern_bullish',
    'roc_momentum_shift',
    'roc_negative',
    'roc_positive',
    'rsi_bearish_divergence',
    'rsi_bullish_divergence',
    'rsi_cross_down',
    'rsi_cross_up',
    'rsi_hidden_bearish_divergence',
    'rsi_hidden_bullish_divergence',
    'rsi_overbought',
    'rsi_oversold',
    'shooting_star_trigger',
    'sma_cross_down',
    'sma_cross_up',
    'sma_crossover',
    'smart_money_holdings_cross',
    'smart_money_holdings_rising',
    'smart_money_inflow_spike',
    'smart_money_net_positive',
    'smma_cross_down',
    'smma_cross_up',
    'spinning_top_trigger',
    'starc_lower_breakout',
    'starc_upper_breakout',
    'stc_overbought',
    'stc_oversold',
    'stoch_overbought',
    'stoch_oversold',
    'stochrsi_overbought',
    'stochrsi_oversold',
    'strong_body_recent',
    'supertrend_flip_down',
    'supertrend_flip_up',
    'supertrend_long',
    'supertrend_short',
    't3_cross_down',
    't3_cross_up',
    'tema_cross_down',
    'tema_cross_up',
    'three_black_crows_trigger',
    'three_inside_down_trigger',
    'three_inside_up_trigger',
    'three_white_soldiers_trigger',
    'token_unlock_cliff_ahead',
    'token_unlock_pressure_low',
    'treasury_accumulation_trigger',
    'treasury_growing',
    'trima_cross_down',
    'trima_cross_up',
    'trix_bearish',
    'trix_bullish',
    'tsi_bearish',
    'tsi_bullish',
    'ttm_squeeze_active',
    'ttm_squeeze_fired_bearish',
    'ttm_squeeze_fired_bullish',
    'tweezer_bottoms_trigger',
    'tweezer_tops_trigger',
    'two_bar_reversal_bearish_trigger',
    'two_bar_reversal_bullish_trigger',
    'ulcer_high_risk',
    'ulcer_low_risk',
    'uo_overbought',
    'uo_oversold',
    've_above_upper',
    've_below_lower',
    'volatility_stop_lower',
    'volatility_stop_upper',
    'vortex_bearish',
    'vortex_bullish',
    'vortex_crossover',
    'vpt_bearish',
    'vpt_bullish',
    'vwap_above',
    'vwap_below',
    'vwma_cross_down',
    'vwma_cross_up',
    'whale_accumulation_trigger',
    'whale_net_accumulation',
    'williams_r_overbought',
    'williams_r_oversold',
    'wma_cross_down',
    'wma_cross_up',
)


def test_every_released_name_resolves():
    unresolvable = sorted(n for n in RELEASED_SIGNAL_NAMES if not RuleRegistry.has(n))
    assert not unresolvable, (
        "these released signal names no longer resolve, so any saved strategy using one "
        "silently evaluates it as False: " + ", ".join(unresolvable)
    )


def test_every_alias_points_at_something_registered():
    dangling = sorted(
        f"{old} -> {new}"
        for old, new in RuleRegistry._aliases.items()
        if new not in RuleRegistry.names()
    )
    assert not dangling, "aliases whose target is not registered: " + ", ".join(dangling)


def test_the_frozen_set_covers_everything_registered_today():
    missing = sorted(set(RuleRegistry.names()) - set(RELEASED_SIGNAL_NAMES))
    assert not missing, (
        "signals registered but absent from RELEASED_SIGNAL_NAMES; add them so a later "
        "rename cannot drop them silently: " + ", ".join(missing)
    )
